import type { DbClient } from '@/lib/db';
import { resolveOpenAiKey } from '@/lib/openai';

// ── Types ────────────────────────────────────────────────────────────────────

export interface CreateConsultationInput {
  patientId: string;
  gpId: string;
  date: string;
  consultationType?: string;
  duration?: number;
  summary: string;
  subjectiveNote?: string;
  objectiveNote?: string;
  assessmentNote?: string;
  planNote?: string;
  treatmentPlan?: string;
  prescriptions?: string[];
  referrals?: string[];
  followUp?: string;
  mbsItems?: string[];
  notes?: string;
  aiGenerated?: boolean;
}

export interface SOAPInput {
  notes: string;
  includeMetrics?: boolean;
  includeGuidelines?: boolean;
}

export interface SOAPNote {
  subjective: string;
  objective: string;
  assessment: string;
  plan: string;
  disclaimer: string;
}

export interface Consultation {
  id: string;
  patientId: string;
  gpId: string;
  date: string;
  consultationType: string;
  duration?: number;
  summary: string;
  subjectiveNote?: string;
  objectiveNote?: string;
  assessmentNote?: string;
  planNote?: string;
  treatmentPlan?: string;
  prescriptions: string[];
  referrals: string[];
  followUp?: string;
  mbsItems: string[];
  notes?: string;
  aiGenerated: boolean;
}

// ── Constants ────────────────────────────────────────────────────────────────

const VALID_CONSULTATION_TYPES = new Set([
  'INITIAL',
  'FOLLOW_UP',
  'REVIEW',
  'EMERGENCY',
]);

const SOAP_MODEL = process.env.OPENAI_GP_CHAT_MODEL || 'gpt-4o';

const SOAP_DISCLAIMER =
  'AI-ASSISTED — REQUIRES GP REVIEW. This SOAP note was generated by an AI model and is intended as decision SUPPORT, not decision REPLACEMENT. The treating GP must review, verify, and approve all content before it becomes part of the medical record.';

const SOAP_SYSTEM_PROMPT = [
  "You are an AI scribe for Australian GPs. Generate a structured SOAP note from the provided patient data and GP notes.",
  '',
  'S (Subjective): Patient-reported symptoms, concerns, and history. Draw from symptom journal data.',
  'O (Objective): Vital signs, examination findings, lab results. Draw from health metrics.',
  'A (Assessment): Clinical assessment and differential diagnoses. Consider menopause status.',
  'P (Plan): Treatment plan, investigations, referrals, follow-up. Include MBS item numbers where relevant.',
  '',
  'Format: Markdown with clear section headers. Prefix the assessment with "AI-ASSISTED — REQUIRES GP REVIEW".',
  'Be specific. Reference relevant guidelines. Note: This is decision SUPPORT, not decision REPLACEMENT.',
].join('\n');

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Parses a YYYY-MM-DD string to a Date. Throws on invalid input. */
function parseDateString(value: string): Date {
  if (!value || typeof value !== 'string') {
    throw new Error(`Invalid date: "${value}"`);
  }

  const trimmed = value.trim();
  const date = new Date(`${trimmed}T00:00:00.000Z`);
  if (Number.isNaN(date.getTime())) {
    throw new Error(`Invalid date: "${trimmed}"`);
  }

  return date;
}

/** Formats a Date as YYYY-MM-DD. */
function formatDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

/**
 * Maps a raw Prisma GPConsultation row (with `Date` fields) to the domain
 * `Consultation` interface (with ISO 8601 strings).
 */
function mapConsultation(row: {
  id: string;
  patientId: string;
  gpId: string;
  date: Date;
  consultationType: string;
  duration: number | null;
  summary: string;
  subjectiveNote: string | null;
  objectiveNote: string | null;
  assessmentNote: string | null;
  planNote: string | null;
  treatmentPlan: string | null;
  prescriptions: string[];
  referrals: string[];
  followUp: Date | null;
  mbsItems: string[];
  notes: string | null;
  aiGenerated: boolean;
}): Consultation {
  return {
    id: row.id,
    patientId: row.patientId,
    gpId: row.gpId,
    date: formatDate(row.date),
    consultationType: row.consultationType,
    duration: row.duration ?? undefined,
    summary: row.summary,
    subjectiveNote: row.subjectiveNote ?? undefined,
    objectiveNote: row.objectiveNote ?? undefined,
    assessmentNote: row.assessmentNote ?? undefined,
    planNote: row.planNote ?? undefined,
    treatmentPlan: row.treatmentPlan ?? undefined,
    prescriptions: row.prescriptions,
    referrals: row.referrals,
    followUp: row.followUp ? row.followUp.toISOString() : undefined,
    mbsItems: row.mbsItems,
    notes: row.notes ?? undefined,
    aiGenerated: row.aiGenerated,
  };
}

/**
 * Builds a clinical context string for the SOAP generation prompt
 * from patient profile, recent symptoms, health metrics, and medications.
 */
async function buildPatientContext(
  db: DbClient,
  patientId: string,
  includeMetrics: boolean,
): Promise<string> {
  const parts: string[] = [];

  // ── Patient profile ─────────────────────────────────────────────────
  const profile = await db.healthProfile.findUnique({
    where: { id: patientId },
    select: {
      dateOfBirth: true,
      sexAtBirth: true,
      menopauseStatus: true,
      heightCm: true,
      weightKg: true,
      bloodType: true,
      allergies: true,
      chronicConditions: true,
      currentMedications: true,
      smokingStatus: true,
      alcoholUnitsPerWeek: true,
      exerciseMinutesPerWeek: true,
      familyHistory: true,
    },
  });

  if (profile) {
    const profileLines: string[] = ['PATIENT PROFILE:'];
    if (profile.dateOfBirth) {
      const age = Math.floor(
        (Date.now() - profile.dateOfBirth.getTime()) /
          (365.25 * 24 * 60 * 60 * 1000),
      );
      profileLines.push(`- Age: ${age} (DOB: ${formatDate(profile.dateOfBirth)})`);
    }
    if (profile.sexAtBirth) {
      profileLines.push(`- Sex at birth: ${profile.sexAtBirth}`);
    }
    if (profile.menopauseStatus) {
      profileLines.push(`- Menopause status: ${profile.menopauseStatus}`);
    }
    if (profile.heightCm) {
      profileLines.push(`- Height: ${profile.heightCm} cm`);
    }
    if (profile.weightKg) {
      profileLines.push(`- Weight: ${profile.weightKg} kg`);
      if (profile.heightCm) {
        const bmi = profile.weightKg / ((profile.heightCm / 100) ** 2);
        profileLines.push(`- BMI: ${bmi.toFixed(1)}`);
      }
    }
    if (profile.bloodType) {
      profileLines.push(`- Blood type: ${profile.bloodType}`);
    }
    if (profile.allergies.length > 0) {
      profileLines.push(`- Allergies: ${profile.allergies.join(', ')}`);
    }
    if (profile.chronicConditions.length > 0) {
      profileLines.push(`- Chronic conditions: ${profile.chronicConditions.join(', ')}`);
    }
    if (profile.smokingStatus) {
      profileLines.push(`- Smoking status: ${profile.smokingStatus}`);
    }
    if (profile.alcoholUnitsPerWeek !== null) {
      profileLines.push(`- Alcohol: ${profile.alcoholUnitsPerWeek} units/week`);
    }
    if (profile.exerciseMinutesPerWeek !== null) {
      profileLines.push(`- Exercise: ${profile.exerciseMinutesPerWeek} min/week`);
    }
    if (profile.familyHistory) {
      profileLines.push(`- Family history: ${JSON.stringify(profile.familyHistory)}`);
    }
    parts.push(profileLines.join('\n'));
  }

  // ── Recent symptoms (last 30 days) ──────────────────────────────────
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

  const symptoms = await db.symptomJournal.findMany({
    where: {
      healthProfileId: patientId,
      date: { gte: thirtyDaysAgo },
    },
    orderBy: { date: 'desc' },
  });

  if (symptoms.length > 0) {
    const symptomLines: string[] = ['RECENT SYMPTOMS (last 30 days):'];
    for (const s of symptoms) {
      const severityLabel = s.severity > 0 ? ` (severity: ${s.severity}/10)` : '';
      symptomLines.push(
        `- ${formatDate(s.date)}: ${s.symptomType}${severityLabel}${s.notes ? ` — ${s.notes}` : ''}`,
      );
    }
    parts.push(symptomLines.join('\n'));
  }

  // ── Health metrics (if requested) ───────────────────────────────────
  if (includeMetrics) {
    const metrics = await db.healthMetric.findMany({
      where: { healthProfileId: patientId },
      orderBy: { recordedAt: 'desc' },
      take: 30,
    });

    if (metrics.length > 0) {
      const metricLines: string[] = ['RECENT HEALTH METRICS:'];
      for (const m of metrics) {
        metricLines.push(
          `- ${m.recordedAt.toISOString()}: ${m.metricType} = ${typeof m.value === 'object' ? JSON.stringify(m.value) : String(m.value)}${m.unit ? ` ${m.unit}` : ''}`,
        );
      }
      parts.push(metricLines.join('\n'));
    }
  }

  // ── Active medications ──────────────────────────────────────────────
  const medications = await db.medication.findMany({
    where: {
      healthProfileId: patientId,
      status: { in: ['ACTIVE'] },
    },
    orderBy: { startDate: 'desc' },
  });

  if (medications.length > 0) {
    const medLines: string[] = ['ACTIVE MEDICATIONS:'];
    for (const med of medications) {
      medLines.push(
        `- ${med.name} (${med.type}): ${med.dosage}, ${med.frequency}${med.route ? `, ${med.route}` : ''} — started ${formatDate(med.startDate)}`,
      );
    }
    parts.push(medLines.join('\n'));
  }

  return parts.join('\n\n');
}

/**
 * Parses a SOAP note JSON response from the LLM into structured fields.
 * Falls back gracefully if the parsed JSON is malformed.
 */
function parseSOAPJsonResponse(
  responseText: string,
): Pick<SOAPNote, 'subjective' | 'objective' | 'assessment' | 'plan'> {
  // Try to extract a JSON object from the response (may contain markdown fences)
  let jsonStr = responseText.trim();

  // Remove markdown code fences if present
  const fenceMatch = jsonStr.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
  if (fenceMatch) {
    jsonStr = fenceMatch[1].trim();
  }

  try {
    const parsed = JSON.parse(jsonStr) as Record<string, unknown>;
    return {
      subjective:
        typeof parsed.subjective === 'string' && parsed.subjective.trim()
          ? parsed.subjective.trim()
          : 'No subjective data generated.',
      objective:
        typeof parsed.objective === 'string' && parsed.objective.trim()
          ? parsed.objective.trim()
          : 'No objective data generated.',
      assessment:
        typeof parsed.assessment === 'string' && parsed.assessment.trim()
          ? parsed.assessment.trim()
          : 'No assessment generated.',
      plan:
        typeof parsed.plan === 'string' && parsed.plan.trim()
          ? parsed.plan.trim()
          : 'No plan generated.',
    };
  } catch {
    // Fallback: return the raw text as assessment and note parsing failure
    return {
      subjective:
        'Unable to parse AI response. See raw output in assessment field.',
      objective:
        'Unable to parse AI response. See raw output in assessment field.',
      assessment: responseText.trim(),
      plan: 'Unable to parse AI response. See raw output in assessment field.',
    };
  }
}

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * Creates a new GP consultation record.
 *
 * If `aiGenerated` is true, the data is stored as-provided — no external
 * AI call is made here. Callers should use `generateSOAPNote` separately
 * when SOAP generation is needed.
 *
 * @param db   Database client
 * @param data Consultation input data
 * @returns    The created consultation (domain representation)
 */
export async function createConsultation(
  db: DbClient,
  data: CreateConsultationInput,
): Promise<Consultation> {
  // ── Validate required fields ─────────────────────────────────────────
  if (!data.patientId || typeof data.patientId !== 'string') {
    throw new Error('patientId is required');
  }

  if (!data.gpId || typeof data.gpId !== 'string') {
    throw new Error('gpId is required');
  }

  if (!data.date || typeof data.date !== 'string') {
    throw new Error('date is required');
  }

  if (!data.summary || typeof data.summary !== 'string' || !data.summary.trim()) {
    throw new Error('summary is required');
  }

  // ── Validate consultation type ───────────────────────────────────────
  const consultationType = data.consultationType?.trim().toUpperCase() || 'INITIAL';
  if (!VALID_CONSULTATION_TYPES.has(consultationType)) {
    throw new Error(
      `Invalid consultationType "${data.consultationType}". Valid values: ${[...VALID_CONSULTATION_TYPES].join(', ')}`,
    );
  }

  // ── Validate duration ────────────────────────────────────────────────
  if (data.duration !== undefined && data.duration !== null) {
    if (typeof data.duration !== 'number' || !Number.isInteger(data.duration) || data.duration < 1) {
      throw new Error('duration must be a positive integer (minutes)');
    }
  }

  // ── Build create payload ─────────────────────────────────────────────
  const createData: Record<string, unknown> = {
    patientId: data.patientId,
    gpId: data.gpId,
    date: parseDateString(data.date),
    consultationType,
    summary: data.summary.trim(),
    prescriptions: data.prescriptions ?? [],
    referrals: data.referrals ?? [],
    mbsItems: data.mbsItems ?? [],
    aiGenerated: data.aiGenerated ?? false,
  };

  if (data.duration !== undefined && data.duration !== null) {
    createData.duration = data.duration;
  }

  if (data.treatmentPlan?.trim()) {
    createData.treatmentPlan = data.treatmentPlan.trim();
  }

  if (data.followUp) {
    createData.followUp = new Date(data.followUp);
  }

  if (data.notes?.trim()) {
    createData.notes = data.notes.trim();
  }

  // ── SOAP fields (optional, provided when saving with AI-generated content)
  if (data.subjectiveNote?.trim()) {
    createData.subjectiveNote = data.subjectiveNote.trim();
  }
  if (data.objectiveNote?.trim()) {
    createData.objectiveNote = data.objectiveNote.trim();
  }
  if (data.assessmentNote?.trim()) {
    createData.assessmentNote = data.assessmentNote.trim();
  }
  if (data.planNote?.trim()) {
    createData.planNote = data.planNote.trim();
  }

  const record = await db.gPConsultation.create({
    data: createData as Parameters<typeof db.gPConsultation.create>[0]['data'],
  });

  return mapConsultation(record as Parameters<typeof mapConsultation>[0]);
}

/**
 * Generates a structured SOAP note using GPT-4o.
 *
 * Fetches patient context (profile, recent symptoms, metrics, and active
 * medications) and combines it with the GP's consultation notes to produce
 * a comprehensive clinical note for review.
 *
 * @param db               Database client
 * @param patientId        The `health_profiles.id` of the patient
 * @param consultationData The GP's notes and generation preferences
 * @returns                Structured SOAP note with disclaimer
 */
export async function generateSOAPNote(
  db: DbClient,
  patientId: string,
  consultationData: SOAPInput,
): Promise<SOAPNote> {
  if (!patientId || typeof patientId !== 'string') {
    throw new Error('patientId is required');
  }

  if (
    !consultationData.notes ||
    typeof consultationData.notes !== 'string' ||
    !consultationData.notes.trim()
  ) {
    throw new Error('notes are required for SOAP generation');
  }

  // ── Resolve API key ──────────────────────────────────────────────────
  const apiKey = await resolveOpenAiKey();
  if (!apiKey) {
    throw new Error(
      'OpenAI API key is not configured. The administrator needs to add an OpenAI API key.',
    );
  }

  // ── Build patient context ────────────────────────────────────────────
  const includeMetrics = consultationData.includeMetrics ?? true;
  const patientContext = await buildPatientContext(db, patientId, includeMetrics);

  // ── Build messages ───────────────────────────────────────────────────
  const userContent = [
    'Generate a comprehensive SOAP note based on the following information.',
    '',
    patientContext || 'No additional patient context available.',
    '',
    'GP NOTES:',
    consultationData.notes.trim(),
    '',
    'Return ONLY a valid JSON object with exactly four string fields: subjective, objective, assessment, plan.',
    'Each field should contain the respective section content in Markdown format.',
    'The assessment field MUST begin with "AI-ASSISTED — REQUIRES GP REVIEW".',
  ].join('\n');

  // ── Call OpenAI ──────────────────────────────────────────────────────
  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: SOAP_MODEL,
      messages: [
        { role: 'system', content: SOAP_SYSTEM_PROMPT },
        { role: 'user', content: userContent },
      ],
      response_format: { type: 'json_object' },
      temperature: 0.5,
      max_tokens: 3000,
    }),
  });

  if (!response.ok) {
    let errorDetail = '';
    try {
      const errorBody = await response.json() as {
        error?: string | { message?: string };
      };
      if (typeof errorBody.error === 'string') {
        errorDetail = errorBody.error;
      } else if (
        errorBody.error &&
        typeof errorBody.error === 'object' &&
        typeof errorBody.error.message === 'string'
      ) {
        errorDetail = errorBody.error.message;
      }
    } catch {
      // ignore parse errors
    }

    const message = errorDetail || `OpenAI API returned status ${response.status}`;
    throw new Error(`SOAP generation failed: ${message}`);
  }

  const data = await response.json() as {
    choices?: {
      message?: {
        content?: string | null;
      };
    }[];
  };

  const content = data.choices?.[0]?.message?.content;
  if (!content || !content.trim()) {
    throw new Error('SOAP generation returned an empty response.');
  }

  // ── Parse and return ─────────────────────────────────────────────────
  const parsed = parseSOAPJsonResponse(content);

  return {
    subjective: parsed.subjective,
    objective: parsed.objective,
    assessment: parsed.assessment,
    plan: parsed.plan,
    disclaimer: SOAP_DISCLAIMER,
  };
}

/**
 * Returns consultation history for a patient, ordered by date descending
 * (newest first).
 *
 * @param db        Database client
 * @param patientId The patient's `health_profiles.id`
 * @returns         Array of consultations (domain representation)
 */
export async function getConsultations(
  db: DbClient,
  patientId: string,
): Promise<Consultation[]> {
  if (!patientId || typeof patientId !== 'string') {
    throw new Error('patientId is required');
  }

  const records = await db.gPConsultation.findMany({
    where: { patientId },
    orderBy: { date: 'desc' },
  });

  return records.map((r) =>
    mapConsultation(r as Parameters<typeof mapConsultation>[0]),
  );
}

/**
 * Returns a single consultation by its ID.
 *
 * @param db             Database client
 * @param consultationId The consultation's ID
 * @returns              The consultation, or `null` if not found
 */
export async function getConsultation(
  db: DbClient,
  consultationId: string,
): Promise<Consultation | null> {
  if (!consultationId || typeof consultationId !== 'string') {
    throw new Error('consultationId is required');
  }

  const record = await db.gPConsultation.findUnique({
    where: { id: consultationId },
  });

  if (!record) {
    return null;
  }

  return mapConsultation(record as Parameters<typeof mapConsultation>[0]);
}
