import type { DbClient } from '@/lib/db';
import { resolveOpenAiKey } from '@/lib/openai';

// ── Types ────────────────────────────────────────────────────────────────────

export interface ReferralInput {
  specialistType: string;
  urgency: 'routine' | 'semi-urgent' | 'urgent';
  reasonForReferral: string;
  additionalNotes?: string;
}

export interface ReferralLetter {
  subject: string;
  body: string; // markdown formatted
  specialistType: string;
  urgency: string;
  generatedAt: string;
  disclaimer: string;
}

// ── Constants ────────────────────────────────────────────────────────────────

const REFERRAL_MODEL = process.env.OPENAI_GP_CHAT_MODEL || 'gpt-4o';

const VALID_SPECIALIST_TYPES = new Set([
  'gynaecologist',
  'endocrinologist',
  'psychiatrist',
  'physiotherapist',
  'dietitian',
  'cardiologist',
  'other',
]);

const VALID_URGENCIES = new Set(['routine', 'semi-urgent', 'urgent']);

const DISCLAIMER =
  'This referral letter was generated by an AI assistant and is intended as decision support only. The referring GP must review, verify, and approve all content before sending. Final clinical responsibility rests with the referring GP.';

const SYSTEM_PROMPT = [
  "You are an Australian GP's referral letter assistant. Generate a professional specialist referral letter in standard Australian format.",
  '',
  'Include:',
  '- Referring GP details (placeholder)',
  '- Patient demographics and key history',
  '- Reason for referral',
  '- Relevant clinical findings (symptoms, metrics, lab results)',
  '- Current medications',
  '- Relevant family history',
  '- Urgency level',
  '',
  'Use Australian medical terminology. Be concise but thorough. Include relevant MBS item numbers if applicable.',
  '',
  'Return a JSON object with two fields:',
  '- "subject": A concise subject line for the referral letter',
  '- "body": The full referral letter body in Markdown format',
].join('\n');

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Formats a Date as YYYY-MM-DD. */
function formatDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

/** Computes age in years from a Date object. */
function computeAge(dateOfBirth: Date): number {
  const today = new Date();
  let age = today.getUTCFullYear() - dateOfBirth.getUTCFullYear();
  const monthDelta = today.getUTCMonth() - dateOfBirth.getUTCMonth();
  if (monthDelta < 0 || (monthDelta === 0 && today.getUTCDate() < dateOfBirth.getUTCDate())) {
    age -= 1;
  }
  return age;
}

interface RawApiResponse {
  subject?: string;
  body?: string;
}

/**
 * Builds a comprehensive patient context string for the referral letter prompt.
 * Gathers profile, recent symptoms, health metrics, medications, lab results,
 * and recent consultation summaries.
 */
async function buildPatientContext(
  db: DbClient,
  patientId: string,
): Promise<string> {
  const parts: string[] = [];

  // ── Health profile ─────────────────────────────────────────────────
  const profile = await db.healthProfile.findUnique({
    where: { id: patientId },
    select: {
      dateOfBirth: true,
      sexAtBirth: true,
      menopauseStatus: true,
      heightCm: true,
      weightKg: true,
      bloodType: true,
      allergies: true,
      chronicConditions: true,
      currentMedications: true,
      smokingStatus: true,
      alcoholUnitsPerWeek: true,
      exerciseMinutesPerWeek: true,
      familyHistory: true,
    },
  });

  if (!profile) {
    throw new Error(`Health profile not found for patient: ${patientId}`);
  }

  const profileLines: string[] = ['PATIENT PROFILE:'];
  if (profile.dateOfBirth) {
    const age = computeAge(profile.dateOfBirth);
    profileLines.push(`- Age: ${age} (DOB: ${formatDate(profile.dateOfBirth)})`);
  }
  if (profile.sexAtBirth) {
    profileLines.push(`- Sex at birth: ${profile.sexAtBirth}`);
  }
  if (profile.menopauseStatus) {
    profileLines.push(`- Menopause status: ${profile.menopauseStatus}`);
  }
  if (profile.heightCm) {
    profileLines.push(`- Height: ${profile.heightCm} cm`);
  }
  if (profile.weightKg) {
    profileLines.push(`- Weight: ${profile.weightKg} kg`);
    if (profile.heightCm) {
      const bmi = profile.weightKg / ((profile.heightCm / 100) ** 2);
      profileLines.push(`- BMI: ${bmi.toFixed(1)}`);
    }
  }
  if (profile.bloodType) {
    profileLines.push(`- Blood type: ${profile.bloodType}`);
  }
  if (profile.allergies.length > 0) {
    profileLines.push(`- Allergies: ${profile.allergies.join(', ')}`);
  }
  if (profile.chronicConditions.length > 0) {
    profileLines.push(`- Chronic conditions: ${profile.chronicConditions.join(', ')}`);
  }
  if (profile.currentMedications.length > 0) {
    profileLines.push(`- Current medications (profile): ${profile.currentMedications.join(', ')}`);
  }
  if (profile.smokingStatus) {
    profileLines.push(`- Smoking status: ${profile.smokingStatus}`);
  }
  if (profile.alcoholUnitsPerWeek !== null) {
    profileLines.push(`- Alcohol: ${profile.alcoholUnitsPerWeek} units/week`);
  }
  if (profile.exerciseMinutesPerWeek !== null) {
    profileLines.push(`- Exercise: ${profile.exerciseMinutesPerWeek} min/week`);
  }
  if (profile.familyHistory) {
    profileLines.push(`- Family history: ${JSON.stringify(profile.familyHistory)}`);
  }
  parts.push(profileLines.join('\n'));

  // ── Recent symptoms (30 days) ──────────────────────────────────────
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

  const symptoms = await db.symptomJournal.findMany({
    where: {
      healthProfileId: patientId,
      date: { gte: thirtyDaysAgo },
    },
    orderBy: { date: 'desc' },
  });

  if (symptoms.length > 0) {
    const symptomLines: string[] = ['RECENT SYMPTOMS (last 30 days):'];
    for (const s of symptoms) {
      const severityLabel = s.severity > 0 ? ` (severity: ${s.severity}/10)` : '';
      symptomLines.push(
        `- ${formatDate(s.date)}: ${s.symptomType}${severityLabel}${s.notes ? ` — ${s.notes}` : ''}`,
      );
    }
    parts.push(symptomLines.join('\n'));
  }

  // ── Health metrics (recent, up to 20 entries) ──────────────────────
  const metrics = await db.healthMetric.findMany({
    where: { healthProfileId: patientId },
    orderBy: { recordedAt: 'desc' },
    take: 20,
  });

  if (metrics.length > 0) {
    const metricLines: string[] = ['RECENT HEALTH METRICS:'];
    for (const m of metrics) {
      const valueStr =
        typeof m.value === 'object' && m.value !== null
          ? JSON.stringify(m.value)
          : String(m.value);
      metricLines.push(
        `- ${m.recordedAt.toISOString()}: ${m.metricType} = ${valueStr}${m.unit ? ` ${m.unit}` : ''}`,
      );
    }
    parts.push(metricLines.join('\n'));
  }

  // ── Active medications (detailed) ──────────────────────────────────
  const medications = await db.medication.findMany({
    where: {
      healthProfileId: patientId,
      status: { in: ['ACTIVE'] },
    },
    orderBy: { startDate: 'desc' },
  });

  if (medications.length > 0) {
    const medLines: string[] = ['DETAILED ACTIVE MEDICATIONS:'];
    for (const med of medications) {
      medLines.push(
        `- ${med.name} (${med.type}): ${med.dosage}, ${med.frequency}${med.route ? `, ${med.route}` : ''} — started ${formatDate(med.startDate)}`,
      );
    }
    parts.push(medLines.join('\n'));
  }

  // ── Lab results (most recent) ──────────────────────────────────────
  const labResults = await db.labResult.findMany({
    where: { healthProfileId: patientId },
    orderBy: { testDate: 'desc' },
    take: 10,
  });

  if (labResults.length > 0) {
    const labLines: string[] = ['RECENT LAB RESULTS:'];
    for (const lab of labResults) {
      labLines.push(
        `- ${formatDate(lab.testDate)}: ${lab.testName} = ${lab.resultValue}${lab.unit ? ` ${lab.unit}` : ''} (ref: ${lab.referenceRange ?? 'N/A'})${lab.isAbnormal ? ' — ABNORMAL' : ''}`,
      );
    }
    parts.push(labLines.join('\n'));
  }

  // ── Recent consultations (last 5) ──────────────────────────────────
  const consultations = await db.gPConsultation.findMany({
    where: { patientId },
    orderBy: { date: 'desc' },
    take: 5,
  });

  if (consultations.length > 0) {
    const consultLines: string[] = ['RECENT GP CONSULTATIONS:'];
    for (const c of consultations) {
      consultLines.push(
        `- ${formatDate(c.date)} [${c.consultationType}]: ${c.summary}`,
      );
    }
    parts.push(consultLines.join('\n'));
  }

  return parts.join('\n\n');
}

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * Generates a specialist referral letter for a patient using GPT-4o.
 *
 * Fetches comprehensive patient context (profile, symptoms, metrics,
 * medications, lab results, and recent consultations) and generates
 * a professional Australian-format referral letter.
 *
 * The returned letter body is formatted in Markdown. The referring GP must
 * review and approve the content before sending.
 *
 * @param db           Database client
 * @param patientId    The `health_profiles.id` of the patient
 * @param referralData Referral input data (specialist type, urgency, reason)
 * @returns            A structured referral letter with markdown body
 */
export async function generateReferralLetter(
  db: DbClient,
  patientId: string,
  referralData: ReferralInput,
): Promise<ReferralLetter> {
  // ── Validate inputs ──────────────────────────────────────────────────
  if (!patientId || typeof patientId !== 'string') {
    throw new Error('patientId is required');
  }

  if (
    !referralData.specialistType ||
    typeof referralData.specialistType !== 'string'
  ) {
    throw new Error('specialistType is required');
  }

  if (!VALID_SPECIALIST_TYPES.has(referralData.specialistType)) {
    throw new Error(
      `Invalid specialistType "${referralData.specialistType}". Valid values: ${[...VALID_SPECIALIST_TYPES].join(', ')}`,
    );
  }

  if (
    !referralData.urgency ||
    !VALID_URGENCIES.has(referralData.urgency)
  ) {
    throw new Error(
      `Invalid urgency "${referralData.urgency}". Valid values: ${[...VALID_URGENCIES].join(', ')}`,
    );
  }

  if (
    !referralData.reasonForReferral ||
    typeof referralData.reasonForReferral !== 'string' ||
    !referralData.reasonForReferral.trim()
  ) {
    throw new Error('reasonForReferral is required');
  }

  // ── Resolve API key ──────────────────────────────────────────────────
  const apiKey = await resolveOpenAiKey();
  if (!apiKey) {
    throw new Error(
      'OpenAI API key is not configured. The administrator needs to add an OpenAI API key.',
    );
  }

  // ── Build patient context ────────────────────────────────────────────
  const patientContext = await buildPatientContext(db, patientId);

  // ── Build user prompt ────────────────────────────────────────────────
  const userContentParts = [
    `Generate a specialist referral letter to a ${referralData.specialistType}.`,
    '',
    `Urgency: ${referralData.urgency.toUpperCase()}`,
    `Reason for referral: ${referralData.reasonForReferral.trim()}`,
  ];

  if (referralData.additionalNotes?.trim()) {
    userContentParts.push(
      '',
      `Additional notes: ${referralData.additionalNotes.trim()}`,
    );
  }

  userContentParts.push(
    '',
    'PATIENT DATA:',
    patientContext || 'No patient data available.',
    '',
    'Return a JSON object with two string fields: "subject" and "body".',
    'The "body" should be a complete referral letter in Markdown format.',
    'Do not include any text outside the JSON object.',
  );

  const userContent = userContentParts.join('\n');

  // ── Call OpenAI ──────────────────────────────────────────────────────
  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: REFERRAL_MODEL,
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: userContent },
      ],
      response_format: { type: 'json_object' },
      temperature: 0.5,
      max_tokens: 4000,
    }),
  });

  if (!response.ok) {
    let errorDetail = '';
    try {
      const errorBody = (await response.json()) as {
        error?: { message?: string };
      };
      if (errorBody.error?.message) {
        errorDetail = errorBody.error.message;
      }
    } catch {
      // ignore parse errors
    }
    const message =
      errorDetail || `OpenAI API returned status ${response.status}`;
    throw new Error(`Referral letter generation failed: ${message}`);
  }

  const data = (await response.json()) as {
    choices?: { message?: { content?: string | null } }[];
  };

  const content = data.choices?.[0]?.message?.content;
  if (!content || !content.trim()) {
    throw new Error('Referral letter generation returned an empty response.');
  }

  // ── Parse response ───────────────────────────────────────────────────
  let parsed: RawApiResponse;
  try {
    parsed = JSON.parse(content) as RawApiResponse;
  } catch {
    throw new Error('Failed to parse referral letter response as JSON');
  }

  const subject =
    typeof parsed.subject === 'string' && parsed.subject.trim()
      ? parsed.subject.trim()
      : `Referral: ${referralData.specialistType} — ${referralData.reasonForReferral.trim().slice(0, 80)}`;

  const body =
    typeof parsed.body === 'string' && parsed.body.trim()
      ? parsed.body.trim()
      : 'Unable to generate referral letter body. The AI returned an empty response.';

  return {
    subject,
    body,
    specialistType: referralData.specialistType,
    urgency: referralData.urgency,
    generatedAt: new Date().toISOString(),
    disclaimer: DISCLAIMER,
  };
}
